### ISSUE TITLE
auth0 stability

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests-api#21]
@danielfdsilva The auth0 management token seems to be changing frequently. This results in the `/users` endpoint to return `Internal Server Error`: https://imagery-coordination.herokuapp.com/users because the `AUTH0_MANAGE_TOKEN` is not correct for the API app. 

Is there an account setting that is not configured properly on our account? I added you to my auth0 account as a dashboard admin so you have access.

**Comment by danielfdsilva** [comment]
@smit1678 Auth0 changed the way management tokens work. They now expire after a day and getting them from the documentation page is not reliable anymore.
Instead, every time a token is needed we request one and cache it for a day.
You'll need to perform some changes in the auth0 configuration. I updated the README.md, please check if it's clear and let me know if you have any questions.

PR: https://github.com/hotosm/imagery-requests-api/pull/23

**Comment by smit1678** [comment]
@danielfdsilva Ok great. These make sense and are straight forward. Will get these changes made on our account.
